/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package berlangadiaz.vidforge.downloader;

// IMPORTACIONES NECESARIAS (¡Añadidas!)
import javax.swing.SwingWorker;
import java.util.List;
import java.util.ArrayList;
import java.io.File;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;
import java.lang.ProcessBuilder;
import java.lang.Process;

/**
 *
 * @author jaimeberlangadiaz
 */
public class MainViewPanel extends javax.swing.JPanel {

    // ¡CORREGIDO! Esta es la ÚNICA declaración
    private String ultimoArchivoDescargado = "";
    
    // (Esta variable la necesitarás para el 'parentFrame' de PreferenciasPanel, 
    // la añado aquí para que el código compile si lo usas)
    private MainFrame parentFrame; 

    /**
     * Creates new form MainViewPanel
     * * ¡CORREGIDO! He añadido el 'MainFrame parent' al constructor, 
     * ya que lo necesitarás para que funcione el intercambio de paneles.
     */
    public MainViewPanel(MainFrame parent) { 
        initComponents();
        this.parentFrame = parent; 
        
        // 1. Obtener la acción de "pegar" que ya existe en Swing
        javax.swing.Action pasteAction = txtUrl.getActionMap().get("paste");

        // 2. Definir la combinación de teclas "Comando + V"
        // (META_DOWN_MASK es la tecla "Comando" en Java para Mac)
        javax.swing.KeyStroke commandV = javax.swing.KeyStroke.getKeyStroke(
                java.awt.event.KeyEvent.VK_V,
                java.awt.event.InputEvent.META_DOWN_MASK
        );

        // 3. Registrar "Comando + V" para que ejecute la acción de "pegar"
        txtUrl.getInputMap().put(commandV, "paste");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        chkSoloAudio = new javax.swing.JCheckBox();
        rbVideo1080 = new javax.swing.JRadioButton();
        rbVideoMejor = new javax.swing.JRadioButton();
        btnDescargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        btnAbrirVideo = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        rbVideo720 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbAudioBuena = new javax.swing.JRadioButton();
        rbAudioNormal = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cmbFormato = new javax.swing.JComboBox<>();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        setLayout(null);

        jLabel1.setText("Url del Vídeo:");
        add(jLabel1);
        jLabel1.setBounds(20, 30, 80, 20);

        txtUrl.setText("Pega Aquí la URL del Vídeo");
        add(txtUrl);
        txtUrl.setBounds(100, 30, 440, 23);

        chkSoloAudio.setText("Descargar solo audio (mp3)");
        chkSoloAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSoloAudioActionPerformed(evt);
            }
        });
        add(chkSoloAudio);
        chkSoloAudio.setBounds(20, 70, 190, 21);

        buttonGroup1.add(rbVideo1080);
        rbVideo1080.setText("1080p");
        add(rbVideo1080);
        rbVideo1080.setBounds(270, 130, 80, 20);

        buttonGroup1.add(rbVideoMejor);
        rbVideoMejor.setSelected(true);
        rbVideoMejor.setText("Mejor Disponible");
        rbVideoMejor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVideoMejorActionPerformed(evt);
            }
        });
        add(rbVideoMejor);
        rbVideoMejor.setBounds(130, 130, 130, 21);

        btnDescargar.setText("Descargar");
        btnDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescargarActionPerformed(evt);
            }
        });
        add(btnDescargar);
        btnDescargar.setBounds(10, 260, 100, 40);

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 300, 480, 130);

        btnAbrirVideo.setText("Reproducir último archivo descargado");
        btnAbrirVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirVideoActionPerformed(evt);
            }
        });
        add(btnAbrirVideo);
        btnAbrirVideo.setBounds(10, 430, 290, 23);

        progressBar.setStringPainted(true);
        add(progressBar);
        progressBar.setBounds(110, 280, 380, 20);

        jLabel2.setText("Calidad de Video:");
        add(jLabel2);
        jLabel2.setBounds(20, 120, 110, 30);

        buttonGroup1.add(rbVideo720);
        rbVideo720.setText("720p");
        rbVideo720.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVideo720ActionPerformed(evt);
            }
        });
        add(rbVideo720);
        rbVideo720.setBounds(350, 130, 70, 21);

        jLabel3.setText("Calidad de Audio (solo si es mp3):");
        add(jLabel3);
        jLabel3.setBounds(20, 100, 210, 17);

        buttonGroup2.add(rbAudioBuena);
        rbAudioBuena.setSelected(true);
        rbAudioBuena.setText("Buena (192kbps)");
        add(rbAudioBuena);
        rbAudioBuena.setBounds(240, 100, 130, 21);

        buttonGroup2.add(rbAudioNormal);
        rbAudioNormal.setText("Normal (128kbps)");
        add(rbAudioNormal);
        rbAudioNormal.setBounds(390, 100, 130, 21);

        jLabel4.setText("Formato de Salida: ");
        add(jLabel4);
        jLabel4.setBounds(20, 160, 130, 40);

        cmbFormato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mp4", "mkv", "webm", "mp3" }));
        add(cmbFormato);
        cmbFormato.setBounds(160, 170, 72, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void chkSoloAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSoloAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSoloAudioActionPerformed

    private void rbVideoMejorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVideoMejorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVideoMejorActionPerformed

    private void rbVideo720ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVideo720ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVideo720ActionPerformed

    private void btnDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescargarActionPerformed
        //Preparamos la GUI para la descarga
        progressBar.setValue(0);
        txtLog.setText("");
        btnDescargar.setEnabled(false);
        
        //Leemos todas las opciones de la GUI
        String url = txtUrl.getText();
        boolean soloAudio = chkSoloAudio.isSelected();
        String formato = cmbFormato.getSelectedItem().toString();
        
        String calidadVideo = "";
            if (rbVideoMejor.isSelected()){
                calidadVideo = "mejor";
            }   else if (rbVideo1080.isSelected()){
                calidadVideo ="1080p";
            }       else if (rbVideo720.isSelected()){
                calidadVideo ="720p";
        }
        
        String calidadAudio = "";
        if (rbAudioBuena.isSelected()){
            calidadAudio = "buena";
        } else if (rbAudioNormal.isSelected()){
            calidadAudio = "normal";
        }
        
        java.util.List<String> command = new java.util.ArrayList<>();
        
        command.add("/opt/homebrew/bin/yt-dlp");
        
        //logica de opciones
        if (soloAudio){
            command.add("-x");
            command.add("--audio-format");
            command.add(formato);
            
            if (calidadAudio.equals("buena")){
                command.add("--audio-quality");
                command.add("192K");
            }else if (calidadAudio.equals("normal")){
                command.add("--audio-quality");
                command.add("128K");
            } 
        } else { 
            command.add("--merge-output-format");
            command.add(formato);
            
            if (calidadVideo.equals("1080p")){
                command.add("-f");
                command.add("bestvideo[height<=1080]+bestaudio/[height<=1080]");
            } else if (calidadVideo.equals("720p")){
                command.add("-f");
                command.add("bestvideo[height<=720]+bestaudio/best[height<=720]");
            }
            //si es mejor no añadimos nada (es el por defecto)
        }
        //TEMPORAL: ruta de guardado. Más tarde la leemos de preferencias 
        //Guarda en la carpeta de descargas del Usuario
        command.add("-o");
        command.add(System.getProperty("user.home")+ "/Download/%(title)s.%(ext)s");
        
        command.add(url);
        command.add("--ffmpeg-location");
        command.add("/opt/homebrew/bin/");
        
        //Ejecutar el SwingWorker
        DownloadWorker worker = new DownloadWorker(command);
        worker.execute();
    }//GEN-LAST:event_btnDescargarActionPerformed

    private void btnAbrirVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirVideoActionPerformed
        // Primero, comprobamos si la variable "ultimoArchivoDescargado" tiene algo
        if (ultimoArchivoDescargado == null || ultimoArchivoDescargado.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Aún no se ha descargado ningún archivo en esta sesión.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // No seguimos
        }

        try {
            // Creamos un objeto File con la ruta que guardamos
            java.io.File fileToOpen = new java.io.File(ultimoArchivoDescargado);

            // Comprobamos si el archivo existe de verdad
            if (!fileToOpen.exists()) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "No se encuentra el archivo en la ruta: " + ultimoArchivoDescargado,
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Le pide al "Escritorio" que abra ese archivo
            // con el programa por defecto (QuickTime, VLC, etc.)
            java.awt.Desktop.getDesktop().open(fileToOpen);

        } catch (Exception e) {
            // Por si algo falla
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo abrir el archivo. Error: " + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAbrirVideoActionPerformed
    // Clase interna que maneja la descarga en segundo plano (para no congelar la GUI). 
    class DownloadWorker extends javax.swing.SwingWorker<String,String> { 
        
        private java.util.List<String> command;
        
        //Constructor le pasamos el comando que debe de ejecutar:
            public DownloadWorker(java.util.List<String> command){
                this.command = command;
            }
            //Este es el trabajo "Sucio". Se ejecuta por detrás.
            @Override
            protected String doInBackground() throws Exception{
                System.out.println("Ejecutando comando: " + String.join(" ", command));
                
                ProcessBuilder pb = new ProcessBuilder(this.command);
                pb.redirectErrorStream(true);
                
                try{
                    Process process = pb.start();
                    
                    try(java.io.BufferedReader reader = new java.io.BufferedReader(
                        new java.io.InputStreamReader(process.getInputStream()))){
                        
                        String line;
                        while ((line = reader.readLine()) != null) {
                        publish(line);
                        }
                    }
                    
                    int exitCode = process.waitFor();
                    if (exitCode == 0){
                        return "¡¡¡Descarga completada con ÉXITO!!!";
                    } else {
                        return "ERROR: La descarga falló (código de salida: "+ exitCode + ")";
                    }
                } catch (java.io.IOException | InterruptedException e){
                    return "ERROR CRÍTICO" + e.getMessage();
                }
            }
            
            //Aquí si podemos tocar la GUI (actualizar log y barra)
            @Override
            protected void process(java.util.List<String> chunks){
                //añade la linea del log al JTextArea
                for (String line : chunks) {
                    txtLog.append(line + "\n");
                    
                    //Actualizar barra de progreso
                    try {
                        String percStr = null; // Variable para guardar el string del porcentaje
                    
                        if (line.contains("[download]") && line.contains("%")) {
                            // Opción A: Es una línea de progreso de DESCARGA
                            // Ej: "[download]  10.5% of 12.34MiB at 1.23MiB/s ETA 00:08"
                            int pEnd = line.indexOf("%");
                            int pStart = line.lastIndexOf(" ", pEnd) + 1; // Busca el último espacio antes del '%'
                            percStr = line.substring(pStart, pEnd);

                        } else if (line.contains("[ExtractAudio]") && line.contains("%")) {
                            // Opción B: Es una línea de progreso de CONVERSIÓN DE AUDIO
                            // Ej: "[ExtractAudio] file.mp3: 17.1%|..."
                            int pEnd = line.indexOf("%");
                            int pStart = line.lastIndexOf(" ", pEnd); // Busca el espacio...
                            if (pStart == -1) { // Si no hay espacio, busca los ':'
                                 pStart = line.lastIndexOf(":", pEnd);
                            }
                            percStr = line.substring(pStart + 1, pEnd); // +1 para saltar el espacio o los ':'
                        }

                        // Si hemos encontrado un porcentaje, lo actualizamos
                        if (percStr != null) {
                            double percDouble = Double.parseDouble(percStr.trim());
                            int percInt = (int) percDouble;
                            progressBar.setValue(percInt);
                        }
                    
                } catch (Exception e) {
                    // Si falla el parseo de la barra, lo ignoramos
                }

                // --- INICIO: CAPTURAR RUTA FINAL ---
                // yt-dlp nos dice el archivo final en estas líneas:
                try {
                    if (line.contains("[Merger] Merging formats into")) {
                        // Para vídeos que se unen (ej. "Merging formats into "video.mp4"")
                        int start = line.indexOf("\"") + 1;
                        int end = line.lastIndexOf("\"");
                        MainViewPanel.this.ultimoArchivoDescargado = line.substring(start, end);

                    } else if (line.contains("[ExtractAudio] Destination:")) { // <-- ¡¡ESTA ES LA LÍNEA NUEVA!!
                        // Para conversión de audio (ej. a mp3)
                        // Esto SOBREESCRIBE la ruta temporal .webm
                        int start = line.indexOf("Destination:") + "Destination:".length();
                        MainViewPanel.this.ultimoArchivoDescargado = line.substring(start).trim();
                        
                    } else if (line.contains("[download] Destination:") && !line.contains("ExtractAudio")) {
                        // Para descargas directas (SIN conversión)
                        // Solo guarda esta si NO es una línea de ExtractAudio
                        int start = line.indexOf("Destination:") + "Destination:".length();
                        MainViewPanel.this.ultimoArchivoDescargado = line.substring(start).trim();
                    }
                } catch (Exception e) {
                    // Si falla el "parseo", no pasa nada
                    };
                }
            }
                
            //Se ejecuta después de que doInBackground() termine. (Limpieza final)
            @Override
            public void done() {
                try{
                    //mostramos el mensaje de doInBackground
                    String resultado = get();
                    
                    //Mostramos un dialogo emergente con el resultado
                    javax.swing.JOptionPane.showMessageDialog(MainViewPanel.this, resultado, 
                            "Estado de la Descarga", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    //Manejamos cualquier error que ocurra
                    javax.swing.JOptionPane.showMessageDialog(MainViewPanel.this, 
                            "Error al finalizar: " + e.getMessage(),"Error",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                
                //Reactivar el boton de descargar pase lo que pase
                btnDescargar.setEnabled(true);
            }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirVideo;
    private javax.swing.JButton btnDescargar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chkSoloAudio;
    private javax.swing.JComboBox<String> cmbFormato;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JRadioButton rbAudioBuena;
    private javax.swing.JRadioButton rbAudioNormal;
    private javax.swing.JRadioButton rbVideo1080;
    private javax.swing.JRadioButton rbVideo720;
    private javax.swing.JRadioButton rbVideoMejor;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
