package berlangadiaz.vidforge.downloader.view;

import berlangadiaz.vidforge.downloader.view.AboutDialog;
import berlangadiaz.vidforge.downloader.view.MainViewPanel;
import berlangadiaz.vidforge.downloader.view.PreferenciasPanel;
import berlangadiaz.vidforge.downloader.view.BibliotecaPanel;
import berlangadiaz.vidforge.downloader.model.GestorJson;
import berlangadiaz.vidforge.downloader.model.GestorJson.Configuracion;
import berlangadiaz.vidforge.downloader.api.ApiClient; 
import berlangadiaz.vidforge.downloader.api.Usuari;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 * Clase principal de la interfaz gráfica (GUI) y Contenedor Principal (Controller).
 * Este frame inicializa todos los paneles, gestiona el flujo de la aplicación (Login/Vistas)
 * y almacena el estado global, incluyendo las preferencias de descarga y la información de la sesión de la API.
 * @author Jaime Berlanga Diaz
 */
public class MainFrame extends javax.swing.JFrame {
    
    // --- VARIABLES DE VISTA ---
    private LoginPanel loginPanel;
    private MainViewPanel mainViewPanel;
    private PreferenciasPanel panelPreferencias;
    private BibliotecaPanel panelBiblioteca;
    
    // --- VARIABLES DE PREFERENCIAS Y ESTADO ---
    // Valores por defecto al iniciar o si el archivo config.json no existe.
    private String rutaYtDlp = getDefaultYtDlpPath();
    private String rutaGuardado = System.getProperty("user.home") + "/Downloads"; 
    private boolean crearM3u = false;
    private String limiteVelocidad = "";
    
    // --- VARIABLES PARA LA ORDENACIÓN DE LA BIBLIOTECA ---
    private int columnaOrdenActual = 0; 
    private boolean ordenAscendente = true; 

    // --- VARIABLES PARA EL LOGIN ---
    private ApiClient apiClient; // Instancia del cliente
    private String currentJwtToken = null; // Token de la sesión activa
    private Usuari currentUser = null; // Objeto del usuario logueado
    private static final String API_BASE_URL = "https://dimedianetapi9.azurewebsites.net"; // URL Base de la API
 
    /**
     * Constructor principal del MainFrame.
     * Carga las preferencias guardadas, inicializa el cliente API y gestiona el flujo de Auto-Login.
     */
    public MainFrame() {        
        // Carga de preferencias de persistencia (yt-dlp).
        this.rutaGuardado = System.getProperty("user.home")+ "/Downloads";
        GestorJson gestor = new GestorJson(rutaGuardado);
        GestorJson.Configuracion config = gestor.leerConfiguracion();
        
        // Sobreescribir las variables con los valores guardados, o usar defaults si no existe el archivo.
        if (config != null){
            //Cargar los valores del JSON
            this.rutaYtDlp = config.rutaYtDlp;
            this.rutaGuardado = config.rutaGuardado;
            this.crearM3u = config.crearM3u;
            this.limiteVelocidad = config.limiteVelocidad;
        } else {
            //Si el archivo no existe (primera vez), usamos los valores por defecto del sistema
            this.rutaYtDlp = getDefaultYtDlpPath();
            //this.rutaGuardado ya está inicializada arriba
            this.crearM3u = false;
            this.limiteVelocidad = "";
        }
        // Inicialización de ApiClients yh GUI.
        this.apiClient = new ApiClient(API_BASE_URL);
        
        initComponents();
        setLocationRelativeTo(null);
        
        //Inicialización de Paneles
        mainViewPanel = new MainViewPanel(this);
        loginPanel = new LoginPanel(this);
        panelPreferencias = new PreferenciasPanel(this);
        panelBiblioteca = new BibliotecaPanel(this);
        //Muestra MainViewPanel por defecto (será ocultado si hay Login).
        panelContenedor.add(mainViewPanel, java.awt.BorderLayout.CENTER);
        
        //Lógica de Auto-Login y Flujo de Vista
        String token = GestorJson.getToken();
        long expiration = GestorJson.getTokenExpirationTime();
        
        if (token != null && !token.isEmpty() && System.currentTimeMillis() < expiration){
            // Token válido: Intentamos reanudar la sesión
            try {
                this.resumeSession(token); 
                mostrarVistaPrincipal();
            } catch (Exception e) {
                 // Si falla (si el token expiró en el servidor o fue inválido),
                 // forzamos el Login.
                 GestorJson.clearToken();
                 mostrarVistaLogin();
            }
        } else {
            // Token no existe o expiró: Muestra el Login.
            mostrarVistaLogin();
        }
       
        
        panelContenedor.revalidate();
        panelContenedor.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        panelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemLogout = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        menuVer = new javax.swing.JMenu();
        itemMostrarDescarga = new javax.swing.JMenuItem();
        itemMostrarBiblioteca = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        itemPreferencias = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAcerdaDe = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VidForge Downloader");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        panelContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContenedor);
        panelContenedor.setBounds(0, 0, 630, 550);

        jMenuBar1.setPreferredSize(new java.awt.Dimension(128, 30));

        menuArchivo.setText("Archivo");

        itemLogout.setText("Cerrar Sesión");
        itemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogoutActionPerformed(evt);
            }
        });
        menuArchivo.add(itemLogout);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(itemSalir);

        jMenuBar1.add(menuArchivo);

        menuVer.setText("Ver");

        itemMostrarDescarga.setText("Panel De Descargas");
        itemMostrarDescarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarDescargaActionPerformed(evt);
            }
        });
        menuVer.add(itemMostrarDescarga);

        itemMostrarBiblioteca.setText("Biblioteca");
        itemMostrarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMostrarBibliotecaActionPerformed(evt);
            }
        });
        menuVer.add(itemMostrarBiblioteca);

        jMenuBar1.add(menuVer);

        menuEditar.setText("Editar");

        itemPreferencias.setText("Preferencias");
        itemPreferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPreferenciasActionPerformed(evt);
            }
        });
        menuEditar.add(itemPreferencias);

        jMenuBar1.add(menuEditar);

        menuAyuda.setText("Ayuda");

        itemAcerdaDe.setText("Acerca De..");
        itemAcerdaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcerdaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(itemAcerdaDe);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemPreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPreferenciasActionPerformed
        panelPreferencias.cargarPreferenciasActuales();   
        panelContenedor.remove(mainViewPanel);
        panelContenedor.remove(panelBiblioteca);
        panelContenedor.add(panelPreferencias, java.awt.BorderLayout.CENTER);
        panelContenedor.revalidate();
        panelContenedor.repaint();
    }//GEN-LAST:event_itemPreferenciasActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        Object[] options = {"Sí", "No"};
        int choice = javax.swing.JOptionPane.showOptionDialog(this, "¿Estás seguro de que desea SALIR?",
                "Confirmar Salida", javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemAcerdaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcerdaDeActionPerformed
        AboutDialog aboutDialog = new AboutDialog(this, true); 
        aboutDialog.setLocationRelativeTo(this); 
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_itemAcerdaDeActionPerformed

    private void itemMostrarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarBibliotecaActionPerformed
        panelBiblioteca.cargarDatosDelJson();
        mostrarVistaBiblioteca();
    }//GEN-LAST:event_itemMostrarBibliotecaActionPerformed

    private void itemMostrarDescargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMostrarDescargaActionPerformed
        mostrarVistaPrincipal();
    }//GEN-LAST:event_itemMostrarDescargaActionPerformed

    private void itemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogoutActionPerformed
        // Limpiar la persistencia
        GestorJson.clearToken(); 
        
        // Limpiar el estado interno del MainFrame
        this.currentJwtToken = null;
        this.currentUser = null;
        
        // Volver al login
        mostrarVistaLogin();
        
        JOptionPane.showMessageDialog(this, 
            "Sesión cerrada con éxito.", 
            "Logout", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_itemLogoutActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // --- MÉTODOS DE SERVICIO (API Y LOGIN) ---

    /**
     * Implementa el proceso de Login completo: autenticación (login) y obtención 
     * de los datos del usuario (getMe).
     *
     * @param email Email del usuario.
     * @param password Contraseña del usuario.
     * @return El objeto {@code Usuari} si el login es exitoso.
     * @throws Exception Si falla la autenticación o la conexión.
     */
    public Usuari attemptLogin(String email, String password) throws Exception {

        String token = apiClient.login(email, password);

        if (token != null && !token.isBlank()) {
            Usuari user = apiClient.getMe(token);

            if (user != null) {
                // Actualizar el estado del MainFrame con la nueva sesión
                this.currentJwtToken = token;
                this.currentUser = user;
                return user;
            }
        }
        // Si falla el login o getMe.
        throw new IOException("Fallo de autenticación o datos de usuario no disponibles.");
    }

    /**
     * Reanuda una sesión previamente guardada utilizando un token JWT persistente.
     * Valida el token llamando al endpoint /getMe de la API.
     *
     * @param token El token JWT a validar.
     * @return El objeto {@code Usuari} si el token es válido.
     * @throws Exception Si el token no es válido o ha expirado en el servidor.
     */
    public Usuari resumeSession(String token) throws Exception {
        Usuari user = apiClient.getMe(token);
        if (user != null) {
            // Si el token es válido, actualizamos el estado
            this.currentJwtToken = token;
            this.currentUser = user;
            return user;
        }
        throw new IOException("Token no válido o expirado en el servidor.");
    }

    /**
     * Devuelve el token JWT activo. Usado por LoginPanel para persistir la sesión.
     *
     * @return El token JWT actual de la sesión.
     */
    public String getCurrentJwtToken() {
        return currentJwtToken;
    }
    
    // --- MÉTODOS DE NAVEGACIÓN Y VISTAS ---
    
    //Método público para cambiar a la vista de la Biblioteca.   
    public void mostrarVistaBiblioteca(){
        //Quita todos los otros paneles
        panelContenedor.remove(panelPreferencias);
        panelContenedor.remove(mainViewPanel);
        panelContenedor.remove(loginPanel);
        
        //Añade el panel de biblioteca
        panelContenedor.add(panelBiblioteca, java.awt.BorderLayout.CENTER);
        panelContenedor.revalidate();
        panelContenedor.repaint();
    }
    
    // Método para mostrar el formulario de inicio de sesión (LoginPanel).
    public void mostrarVistaLogin() {
        panelContenedor.removeAll();

        // Configura el LoginPanel
        loginPanel.clearFields(); 

        panelContenedor.add(loginPanel, java.awt.BorderLayout.CENTER);
        panelContenedor.revalidate();
        panelContenedor.repaint();
        
        // Ocultar los menús al no estar logueado
        if (jMenuBar1 != null) {
            jMenuBar1.setVisible(false);
        }
    }

    // Método para mostrar el panel principal (MainViewPanel).
    public void mostrarVistaPrincipal() {
        panelContenedor.removeAll();
        panelContenedor.add(mainViewPanel, java.awt.BorderLayout.CENTER);
        panelContenedor.revalidate();
        panelContenedor.repaint();

        // Mostrar los menús al estar logueado
        if (jMenuBar1 != null) {
            jMenuBar1.setVisible(true);
        }
    }
    
    /**
     * Devuelve la instancia del panel de la biblioteca.
     * Es esencial para que otras vistas (como MainViewPanel o el DownloadWorker)
     * puedan notificar al panel de la biblioteca que debe recargar la lista
     * después de guardar un nuevo archivo en el log.json.
     * * @return La instancia del {@code BibliotecaPanel}.
     */
    public BibliotecaPanel getPanelBiblioteca() {
        return panelBiblioteca;
    }

    /**
     * Guarda todas las preferencias actuales (rutas, opciones) en las variables de clase
     * y las persiste en el archivo config.json llamando al GestorJson.
     *
     * @param ytDlp Ruta del ejecutable yt-dlp.
     * @param guardado Ruta de la carpeta de guardado de archivos.
     * @param m3u Si se debe crear un archivo M3U (usado para la opción 'Solo Audio').
     * @param limite El límite de velocidad de descarga.
     */
    public void guardarTodasLasPreferencias(String ytDlp, String guardado, boolean m3u, String limite){
        //Guardar en las variables de la clase
        this.setRutaYtDlp(ytDlp);
        this.setRutaGuardado(guardado);
        this.setCrearM3u(m3u);
        this.setLimiteVelocidad(limite);
        
        //Guardar en el archivo JSON
        //Nota: usamos la nueva ruta de guardado (el parámetro 'guardado') para saber dónde
        //poner el config.json.
        try {
            // Guardar en el archivo JSON
            GestorJson gestor = new GestorJson(guardado);
            gestor.guardarConfiguracion(ytDlp, guardado, m3u, limite);
        } catch (IOException e) { // Usamos Exception para simplificar y capturar cualquier error de guardado
            JOptionPane.showMessageDialog(this,
                    "Error al guardar las preferencias. El archivo config.json no se pudo escribir: " + e.getMessage(),
                    "Error de Persistencia", JOptionPane.ERROR_MESSAGE);
        }
    }
 
    /*Determina el comando yt-dlp por defecto basado en el Sistema Operativo
    *Esto asume que el usuario ha instalado la herramienta en su PATH
    *
    * @return "yt-dlp.exe" para windows, o "yt-dlp" para Mac/Linux
    */
    private String getDefaultYtDlpPath() {
        String os = System.getProperty("os.name").toLowerCase();

        if (os.contains("win")) {
            return "yt-dlp.exe";
        } else {
            return "yt-dlp";
        }
    }
    
    //Getters y Setters
    public String getRutaYtDlp(){
        return this.rutaYtDlp;
    }
    public void setRutaYtDlp(String ruta){
        this.rutaYtDlp = ruta;
    }
    
    public String getRutaGuardado(){
        return this.rutaGuardado;
    }
    public void setRutaGuardado(String ruta){
        this.rutaGuardado = ruta;
    }
    public boolean isCrearM3u(){
        return crearM3u;
    }
    public void setCrearM3u(boolean crearM3u){
        this.crearM3u = crearM3u;
    }
    public String getLimiteVelocidad(){
        return limiteVelocidad;
    }
    public void setLimiteVelocidad(String limiteVelocidad){
        this.limiteVelocidad = limiteVelocidad;
    }   
    public int getColumnaOrdenActual(){
        return columnaOrdenActual;
    }
    public void setColumnaOrdenActual(int columnaOrdenActual){
        this.columnaOrdenActual = columnaOrdenActual;
    }
    public boolean isOrdenAscendente(){
        return ordenAscendente;
    }
    public void setOrdenAscendente(boolean ordenAscendente){
        this.ordenAscendente = ordenAscendente;
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAcerdaDe;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JMenuItem itemMostrarBiblioteca;
    private javax.swing.JMenuItem itemMostrarDescarga;
    private javax.swing.JMenuItem itemPreferencias;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuVer;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
