/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package berlangadiaz.vidforge.downloader.view;
import javax.swing.JFileChooser;
import java.io.File;

/**
 *
 * @author jaimeberlangadiaz
 */
public class PreferenciasPanel extends javax.swing.JPanel {

    private MainFrame parentFrame;
    /**
     * Creates new form PreferenciasPanel
     */
    public PreferenciasPanel(MainFrame parent) {
        initComponents();
        spinnerLimite.setModel(new javax.swing.SpinnerNumberModel(0,0,50000,500));
        this.parentFrame = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRutaYtDlp = new javax.swing.JTextField();
        btnBuscarTemporales = new javax.swing.JButton();
        chkCrearM3u = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnBuscarYtDlp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtRutaTemporales = new javax.swing.JTextField();
        spinnerLimite = new javax.swing.JSpinner();

        setLayout(null);

        jLabel1.setText("Ruta de yt-dlp :");
        add(jLabel1);
        jLabel1.setBounds(20, 80, 100, 30);

        txtRutaYtDlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaYtDlpActionPerformed(evt);
            }
        });
        add(txtRutaYtDlp);
        txtRutaYtDlp.setBounds(120, 80, 450, 22);

        btnBuscarTemporales.setText("...");
        btnBuscarTemporales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarTemporales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTemporalesActionPerformed(evt);
            }
        });
        add(btnBuscarTemporales);
        btnBuscarTemporales.setBounds(570, 120, 40, 23);

        chkCrearM3u.setText("Crear .m3u para listas");
        chkCrearM3u.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkCrearM3u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCrearM3uActionPerformed(evt);
            }
        });
        add(chkCrearM3u);
        chkCrearM3u.setBounds(20, 160, 160, 20);

        jLabel2.setText("Límite de velocidad de Descarga (ej. 500K):");
        add(jLabel2);
        jLabel2.setBounds(20, 190, 260, 30);

        btnVolver.setText("Guardar y Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        add(btnVolver);
        btnVolver.setBounds(170, 270, 260, 70);

        btnBuscarYtDlp.setText("...");
        btnBuscarYtDlp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarYtDlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarYtDlpActionPerformed(evt);
            }
        });
        add(btnBuscarYtDlp);
        btnBuscarYtDlp.setBounds(570, 80, 40, 23);

        jLabel3.setText("Ruta de archivos Temporales:");
        add(jLabel3);
        jLabel3.setBounds(20, 120, 180, 20);
        add(txtRutaTemporales);
        txtRutaTemporales.setBounds(200, 120, 370, 22);

        spinnerLimite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(spinnerLimite);
        spinnerLimite.setBounds(280, 190, 64, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarTemporalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTemporalesActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setDialogTitle("Selecciona la carpeta de Archivos Temporales");
        int result = fileChooser.showOpenDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION){
            java.io.File selectedFile = fileChooser.getSelectedFile();
            
            txtRutaTemporales.setText(selectedFile.getAbsolutePath());
        }
        
    }//GEN-LAST:event_btnBuscarTemporalesActionPerformed

    private void chkCrearM3uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCrearM3uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCrearM3uActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        String nuevaRutaYtDlp = txtRutaYtDlp.getText();
        String nuevaRutaGuardado = txtRutaTemporales.getText();
        
        boolean m3u = chkCrearM3u.isSelected();
        String limite = spinnerLimite.getValue().toString();
        
        parentFrame.guardarTodasLasPreferencias(nuevaRutaYtDlp, nuevaRutaGuardado, m3u, limite);
        parentFrame.mostrarVistaPrincipal();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtRutaYtDlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaYtDlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaYtDlpActionPerformed

    private void btnBuscarYtDlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarYtDlpActionPerformed
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Selecciona el ejecutable yt-dlp");
        int result = fileChooser.showOpenDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION){
            java.io.File selectedFile = fileChooser.getSelectedFile();
            
            txtRutaYtDlp.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_btnBuscarYtDlpActionPerformed
    /** 
     * Carga los valores actuales guardados en el MainFrame y los muestra
     * en los Campos de la GUI.
     */
    public void cargarPreferenciasActuales(){
        txtRutaYtDlp.setText(parentFrame.getRutaYtDlp());
        txtRutaTemporales.setText(parentFrame.getRutaGuardado());
        
        chkCrearM3u.setSelected(parentFrame.isCrearM3u());
        String limite = parentFrame.getLimiteVelocidad();
        int valorLimite = 0; //Valor por defecto si hay error
        try {
            //Intenta convertir el String guardado a un número
            if (limite != null && !limite.isEmpty()){
                valorLimite = Integer.parseInt(limite);
            }
        } catch (NumberFormatException e){
                //Si falla (ej. estaba vacío), se queda en 0
        }
        spinnerLimite.setValue(valorLimite);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarTemporales;
    private javax.swing.JButton btnBuscarYtDlp;
    private javax.swing.JButton btnVolver;
    private javax.swing.JCheckBox chkCrearM3u;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner spinnerLimite;
    private javax.swing.JTextField txtRutaTemporales;
    private javax.swing.JTextField txtRutaYtDlp;
    // End of variables declaration//GEN-END:variables
}
