/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package berlangadiaz.vidforge.downloader;

/**
 *
 * @author jaimeberlangadiaz
 */
public class BibliotecaPanel extends javax.swing.JPanel {
    
    private MainFrame parentFrame;
    /**
     * Creates new form BibliotecaPanel
     */
    public BibliotecaPanel(MainFrame parent) {
        initComponents();
        
        //Guardar la referencia del padre
        this.parentFrame = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFiltros = new javax.swing.JPanel();
        tablaArchivos = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelAcciones = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelFiltros.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        add(panelFiltros, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaArchivos.setViewportView(jTable1);

        add(tablaArchivos, java.awt.BorderLayout.CENTER);

        panelAcciones.setMinimumSize(new java.awt.Dimension(100, 100));
        panelAcciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnBuscar.setText("Buscar:");
        panelAcciones.add(btnBuscar);

        txtBuscar.setColumns(20);
        panelAcciones.add(txtBuscar);

        btnBorrar.setText("Borrar Selecionado");
        panelAcciones.add(btnBorrar);

        add(panelAcciones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JScrollPane tablaArchivos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
