/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package berlangadiaz.vidforge.downloader;

/**
 *
 * @author jaimeberlangadiaz
 */
public class BibliotecaPanel extends javax.swing.JPanel {
    
    private MainFrame parentFrame;
    private MediaFileTableModel tableModel;
    /**
     * Creates new form BibliotecaPanel
     */
    public BibliotecaPanel(MainFrame parent) {
        initComponents();
        this.parentFrame = parent;
        
        // Creamos una instancia de nuestro "motor" de tabla
        tableModel = new MediaFileTableModel();
        
        // "Instala" el motor en la JTable que diseñamos
        tablaArchivos.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFiltros = new javax.swing.JPanel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        tablaArchivos = new javax.swing.JTable();
        panelAcciones = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelFiltros.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        add(panelFiltros, java.awt.BorderLayout.PAGE_START);

        tablaArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneTabla.setViewportView(tablaArchivos);

        add(jScrollPaneTabla, java.awt.BorderLayout.CENTER);

        panelAcciones.setMinimumSize(new java.awt.Dimension(100, 100));
        panelAcciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnActualizar.setText("Actualizar Lista");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        panelAcciones.add(btnActualizar);

        btnBuscar.setText("Buscar:");
        panelAcciones.add(btnBuscar);

        txtBuscar.setColumns(20);
        panelAcciones.add(txtBuscar);

        btnBorrar.setText("Borrar Selecionado");
        panelAcciones.add(btnBorrar);

        add(panelAcciones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cargarDatosDelJson();
    }//GEN-LAST:event_btnActualizarActionPerformed
    /**
     * Lee la carpeta de Descargas (guardada en MainFrame),
     * busca archivos de vídeo/audio, y los carga en la JTable.
     */
    public void cargarDatosDelJson() {
        System.out.println("Cargando bliblioteca desde JSON..."); // Mensaje para depuración
        
        //Obtener la ruta de guardado (donde esta el log)
        String rutaCarpetaGuardado = parentFrame.getRutaGuardado();
        
        //LLamar al GestorJson
        GestorJson gestor = new GestorJson(rutaCarpetaGuardado);
        java.util.List<MediaFile> archivos = gestor.leerArchivos();
        
        // Pasar los archivos al "motor" de la tabla
        tableModel.setArchivos(archivos);
        
        System.out.println("Bliblioteca cargada. Encontrados " + archivos.size()+ " registros.");

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JPanel panelAcciones;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JTable tablaArchivos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
