/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package berlangadiaz.vidforge.downloader;
import berlangadiaz.vidforge.downloader.AboutDialog;
/**
 *
 * @author jaimeberlangadiaz
 */
public class MainFrame extends javax.swing.JFrame {
    private MainViewPanel mainViewPanel;
    private PreferenciasPanel panelPreferencias;
    private String rutaYtDlp = getDefaultYtDlpPath();
    private String rutaGuardado = System.getProperty("user.home") + "/Downloads";    
    private boolean crearM3u = false;
    private String limiteVelocidad = "";
    
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        mainViewPanel = new MainViewPanel(this);
        panelPreferencias = new PreferenciasPanel(this);
        panelContenedor.add(mainViewPanel, java.awt.BorderLayout.CENTER);
        
        panelContenedor.revalidate();
        panelContenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        panelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemPreferencias = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        itemAcerdaDe = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VidForge Downloader");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        panelContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelContenedor);
        panelContenedor.setBounds(0, 0, 630, 550);

        jMenu1.setText("Archivo");

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(itemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        itemPreferencias.setText("Preferencias");
        itemPreferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPreferenciasActionPerformed(evt);
            }
        });
        jMenu2.add(itemPreferencias);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Ayuda");

        itemAcerdaDe.setText("Acerca De..");
        itemAcerdaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAcerdaDeActionPerformed(evt);
            }
        });
        jMenu7.add(itemAcerdaDe);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemPreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPreferenciasActionPerformed
        panelPreferencias.cargarPreferenciasActuales();   
        panelContenedor.remove(mainViewPanel);
        panelContenedor.add(panelPreferencias, java.awt.BorderLayout.CENTER);
        panelContenedor.revalidate();
        panelContenedor.repaint();
    }//GEN-LAST:event_itemPreferenciasActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        Object[] options = {"Sí", "No"};
        int choice = javax.swing.JOptionPane.showOptionDialog(this, "¿Estás seguro de que desea SALIR?",
                "Confirmar Salida", javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

        if (choice == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemAcerdaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAcerdaDeActionPerformed
        AboutDialog aboutDialog = new AboutDialog(this, true); 
        aboutDialog.setLocationRelativeTo(this); 
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_itemAcerdaDeActionPerformed
    
    public void mostrarVistaPrincipal() {
        panelContenedor.remove(panelPreferencias);
        panelContenedor.add(mainViewPanel, java.awt.BorderLayout.CENTER);
        panelContenedor.revalidate();
        panelContenedor.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    /*Determina el comando yt-dlp por defecto basado en el Sistema Operativo
    *Esto asume que el usuario ha instalado la herramienta en su PATH
    *
    * @return "yt-dlp.exe" para windows, o "yt-dlp" para Mac/Linux
    */
    private String getDefaultYtDlpPath(){
        String os = System.getProperty("os.name").toLowerCase();
        
        if (os.contains("win")){
            return "yt-dpl.exe";
        }else {
            return "yt-dpl";
        }
    }
    //Getters y Setters
    public String getRutaYtDlp(){
        return this.rutaYtDlp;
    }
    
    public void setRutaYtDlp(String ruta){
        this.rutaYtDlp = ruta;
    }
    
    public String getRutaGuardado(){
        return this.rutaGuardado;
    }
    public void setRutaGuardado(String ruta){
        this.rutaGuardado = ruta;
    }
    public boolean isCrearM3u(){
        return crearM3u;
    }
    public void setCrearM3u(boolean crearM3u){
        this.crearM3u = crearM3u;
    }
    public String getLimiteVelocidad(){
        return limiteVelocidad;
    }
    public void setLimiteVelocidad(String limiteVelocidad){
        this.limiteVelocidad = limiteVelocidad;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAcerdaDe;
    private javax.swing.JMenuItem itemPreferencias;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
